package com.myCompany.soapWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-01-11T18:58:01.775+01:00
 * Generated source version: 3.0.3
 * 
 */
@WebService
public interface CarWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllCars", targetNamespace = "http://soapWebService.myCompany.com/", className = "com.mycompany.myCompany.FindAllCars")
    @WebMethod
    @ResponseWrapper(localName = "findAllCarsResponse", targetNamespace = "http://soapWebService.myCompany.com/", className = "com.myCompany.soapWebService.FindAllCarsResponse")
    public java.util.List<com.myCompany.model.Car> findAllCars();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://soapWebService.myCompany.com/", className = "com.myCompany.soapWebService.Save")
    @WebMethod
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://soapWebService.myCompany.com/", className = "com.myCompany.soapWebService.SaveResponse")
    public long save(
        @WebParam(name = "arg0", targetNamespace = "")
        com.myCompany.model.Car arg0
    );
}
